name: Download Daily Wallpaper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
   
      - name: Download Unslpash daily image
        run: |
          npm i -g unsplash-wallpaper
          cd ./assets/
          unsplash-wallpaper --featured --search wallpapers --daily --width 4096 --height 2160
          mv -fv wallpaper-photo*.jpg unsplash_wallpaper_4k.jpg
          cp unsplash_wallpaper_4k.jpg ./assets/cache/unsplash_wallpaper_1080p.jpg
          
      - name: Download Bing wallpaper
        run: |
          cd ./assets/
          curl "https://bing.ioliu.cn/v1/rand?w=4096&h=2160" -o "bing_wallpaper_4k.jpg"
          cp bing_wallpaper_4k.jpg ./assets/cache/bing_wallpaper_1080p.jpg
      
      - name: Resize Images
        uses: gonzalonaveira/gh-image-resizing@master
        with:
          IMAGES_MAX_WIDTH: "1920"
          IMAGES_FORMATS: "jpg, jpge, png"
          IMAGES_DIRECTORIES: "./assets/cache/"
      
      - name: Delete Cache
        run: |
          cd ./assets/cache/
          mv -fv unsplash_wallpaper_1080p.jpg ./assets/unsplash_wallpaper_1080p.jpg
          mv -fv bing_wallpaper_1080p.jpg ./assets/bing_wallpaper_1080p.jpg
          rm -rf ./assets/cache
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Download Daily Wallpaper'
