name: Sync to Gitee

on:
  schedule:
    - cron: '0 0 * * * '
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
      
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/L1cardo
        dst: gitee/Licardo
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        clone_style: "ssh"
        force_update: true
        debug: true
