name: Sync to Gitee

on:
  schedule:
    - cron: '0 0 * * * '
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
        
    steps:
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: betaflight/betaflight
        src_account_type: org
        dst: gitee/l1cardo
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: "firmware-presets"
        clone_style: "https"
        force_update: true
        debug: true
